### ISSUE TITLE
wont load

### ISSUE THREAD

**Issue by ghost** [MarcLandis/MMM-FlipClock#1]
Failed to load resource: the server responded with a status of 400 ()
localhost/:1 Refused to apply style from 'http://localhost:8080/modules/MMM-FlipClock/resources/flip.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

any ideas?

**Comment by ghost** [comment]
for some reason all the text in the flip.min.css file was all in 1 single line horizontally across, not sure why it did that but i copied the file text and saved it, got it to display something now but all its displaying is the day month and year

**Comment by ghost** [comment]
yeah i cant get this to work, fixed both stil lthe same issues

**Comment by MarcLandis** [comment]
Unfortunately I totally messed up what I uploaded to github. I had it locally on my RPi and uploaded to github from my pc. New version is incoming.

**Comment by MarcLandis** [comment]
Re-uploaded the repo

**Comment by ghost** [comment]
ok will give it a shot thanks for being fast

**Comment by ghost** [comment]
works now, thanks!
